# Generated by Django 4.1.5 on 2023-01-09 18:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='exepts',
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AddField(
            model_name='todo',
            name='exepts',
            field=models.ManyToManyField(related_name='firends', to=settings.AUTH_USER_MODEL),
        ),
    ]
